### PR TITLE
chore: Replace test URL.

### PR DESCRIPTION
**Pull request by Tychristine**
change it to CloudFlare support iPv4&iPv6

### CODE REVIEW

**Review by SukkaW — CHANGES_REQUESTED** [review]
Use `https://cp.cloudflare.com/generate_204`.

**Comment by Tychristine** [comment]
> Use `https://cp.cloudflare.com/generate_204`.

such a good idea.

**Comment by Tychristine** [comment]
```shell
❯ nslookup cp.cloudflare.com
服务器:  one.one.one.one
Address:  2606:4700:4700::1111

非权威应答:
名称:    cp.cloudflare.com
Addresses:  2606:4700::6810:84e5
          2606:4700::6810:85e5
          104.16.133.229
          104.16.132.229
```
Not `1.1.1.1`

**Comment by SukkaW** [comment]
> ```shell
> ❯ nslookup cp.cloudflare.com
> 服务器:  one.one.one.one
> Address:  2606:4700:4700::1111
> 
> 非权威应答:
> 名称:    cp.cloudflare.com
> Addresses:  2606:4700::6810:84e5
>           2606:4700::6810:85e5
>           104.16.133.229
>           104.16.132.229
> ```
> 
> Not `1.1.1.1`

Why stick to 1.1.1.1? `cp.cloudflare.com` is just as good as `1.1.1.1`.

**Pull request merged**
