### PR TITLE
chore: Enable Ad Hoc signing on macOS

### PR DESCRIPTION
**Pull request by i0ntempest**
Closes: https://github.com/clash-verge-rev/clash-verge-rev/issues/1116

### CODE REVIEW

**Comment by MystiPanda** [comment]
这样就可以签名了？有相关文档吗

**Comment by i0ntempest** [comment]
从这里看见的https://github.com/tauri-apps/tauri/issues/8763
我正在用gh action在我的fork上测试 应该是OK

**Review by MystiPanda — APPROVED** [review]

**Comment by cismous2204** [comment]
@i0ntempest 你好，我看到后，在自己的项目中也验证了一下，确实没提示损坏了，但是运行报错了
Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: /opt/homebrew/*/libssl.3.dylib
Referenced from: <697BC101-5BCB-3D55-A8C8-756FAEC76D91> /Applications/苏全效.app/Contents/MacOS/苏全效
Reason: tried: '/opt/homebrew/*/libssl.3.dylib' (code signature in <36E19BFF-6DCD-35E2-B0B6-E78D41FEA3BC> '/opt/homebrew/Cellar/openssl@3/3.3.0/lib/libssl.3.dylib' not valid for use in process: mapping process and mapped file (non-platform) have different Team IDs), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/*/libssl.3.dylib' (no such file), '/opt/homebrew/*/libssl.3.dylib' (code signature in <36E19BFF-6DCD-35E2-B0B6-E78D41FEA3BC> '/opt/homebrew/Cellar/openssl@3/3.3.0/lib/libssl.3.dylib' not valid for use in process: mapping process and mapped file (non-platform) have different Team IDs), '/opt/homebrew/Cellar/openssl@3/3.3.0/lib/libssl.3.dylib' (code signature in <36E19BFF-6DCD-35E2-B0B6-E78D41FEA3BC> '/opt/homebrew/Cellar/openssl@3/3.3.0/lib/libssl.3.dylib' not valid for use
(terminated at launch; ignore backtrace)
想了解到，你没遇到这样的异常吗？

**Comment by cismous2204** [comment]
@MystiPanda 忽略哈，通过原来的issue找到原因了，重新签名了一下，能验证成功，找到关键地方了

**Comment by i0ntempest** [comment]
tauri签名默认开hardened runtime，开了之后签名的app不能随便加载别的dylib
但是为啥你这个编译出来会链接外面的openssl啊（

**Comment by cismous2204** [comment]
@i0ntempest https://github.com/tauri-apps/tauri/pull/9318 这个PR是为了将runtime变成可选项，可以规避这个问题

**Pull request merged**
