### PR TITLE
feat: #1790 使用操作系统默认窗口管理器

### PR DESCRIPTION
**Pull request by witt-bit**
参考#1790

image

Peek 2024-10-29 10-21

### CODE REVIEW

**Comment by Tychristine** [comment]
I built it on this PR branch.
Test it on Windows 11
emmm...It looks like....
image

**Comment by witt-bit** [comment]
> I built it on this PR branch.我在这个 PR 分支上构建了它。 Test it on Windows 11在 Windows 11 上测试 emmm...It looks like.... emmm……看起来好像…… image

Sorry, I rarely use Windows, but it looks OK. This is the window decoration border of Windows itself, which is in line with the style of the operating system.

**Comment by wonfen** [comment]
image
Linux的GNOME下也不美观嘛

**Comment by witt-bit** [comment]
> image Linux的GNOME下也不美观嘛

这是操作系统的窗口管理器呀，你Gnome自己去美化系统呀

**Pull request merged**
