### PR TITLE
chore: added support for compiling linux arm architecture

### PR DESCRIPTION
**Pull request by 1111mp**
Since the migration to `tauri 2.0`, the `linux` system `arm` architecture installation package has not been provided. After testing, the `linux` system `x64` and `arm` architecture packages can be normally built. The build process and results can be viewed: [Alpha Build](https://github.com/1111mp/clash-verge-rev/actions/runs/11550644607)
image

Tried to build `i686-unknown-linux-gnu`, but `libayatana-appindicator3-dev` and `patchelf` do not currently support the `i386` architecture. You can search for package support from https://packages.ubuntu.com/

### CODE REVIEW

**Comment by huzibaca** [comment]
https://github.com/clash-verge-rev/clash-verge-rev/actions/runs/11581673312/job/32242958797   
test failed, please help solve it

**Comment by 1111mp** [comment]
@huzibaca I checked the code of that branch, and there was a missing file `.cargo/config.toml` in the project root directory:
```toml
[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"

[target.armv7-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"
```

**Comment by 1111mp** [comment]
@huzibaca @wonfen Do you have time to test this PR?

**Review by huzibaca — CHANGES_REQUESTED** [review]
The test passed, please remove the relevant debugging code (Setup for linux), I will merge it after the modification is submitted, thank you.

**Comment by 1111mp** [comment]
Debug code has been removed, thanks for your work. 🌹

**Pull request merged**
